[lifequest]
lifequest-vps ansible_host=158.220.90.106 ansible_user=deploy

[lifequest:vars]
ansible_python_interpreter=/usr/bin/python3
app_dir=/opt/life-quest
repo_url=https://github.com/Monthe-prog/Life-Quest.git
app_domain=158.220.90.106
