apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: delete-ingress.yaml
  - path: nodeports.yaml
  - path: local-images.yaml
  - path: vps-config.yaml
